[features]
seeds = true
skip-lint = false

[programs.localnet]
switchboard_buffer = "9PcDy77KoSA9bNNuq7jQMczSmJg8rPFyAT9Ctt2APu3Y"

[programs.devnet]
switchboard_buffer = "9PcDy77KoSA9bNNuq7jQMczSmJg8rPFyAT9Ctt2APu3Y"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/mac/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/switchboard-buffer.ts"
switch = "yarn run ts-node -P ./tsconfig.json runOracle.ts"
server = "yarn run ts-node -P ./tsconfig.json server.ts"


[test.validator]
url = "https://devnet.genesysgo.net/"

#[[test.validator.clone]] # programID
#address = "2TfB33aLaneQb5TNVwyDz3jSZXS6jdW2ARw1Dgf84XCG"
#
#[[test.validator.clone]] # idlAddress
#address = "CKwZcshn4XDvhaWVH9EXnk3iu19t6t5xP2Sy2pD6TRDp"
#
#[[test.validator.clone]] # programState
#address = "BYM81n8HvTJuqZU1PmTVcwZ9G8uoji7FKM6EaPkwphPt"
#
#[[test.validator.clone]] # switchboardVault
#address = "FVLfR6C2ckZhbSwBzZY4CX7YBcddUSge5BNeGQv5eKhy"
#
#[[test.validator.clone]] # tokenWallet
#address = "9mHKsQgdQGUYtZEcve2H5RMyvymyEeAcJJiHzvx6JSeA"
#
#[[test.validator.clone]] # queue
#address = "58ndtWvbcfwmvCVpQGpXUrffPxZmEcKL4xvB8XkMDw5A"
#
#[[test.validator.clone]] # queueAuthority
#address = "3rGrMUKPVp8NzxC7pwxcj4hR3aHmCyKuFFVngH23UYTJ"
#
#[[test.validator.clone]] # queueBuffer
#address = "HtxdQh6CqcMCQfkWaywUhiY4QPjMEFNKwuVEBmrEZX75"
#
#[[test.validator.clone]] # crank
#address = "2wW817yPVJC4SVcMHhjGLc6uGpTXfdweq4z4X3fDBx7q"
#
#[[test.validator.clone]] # crankBuffer
#address = "GBjCv9ux69DCuaUnuDaRBk7RqWs2BhQB7tXxEL2AzYyy"
#
#[[test.validator.clone]] # oracle
#address = "97dSr9qJ45NgfnJ7E1QzB5U8X9QAaqunibAbJVHDt1bq"
#
#[[test.validator.clone]] # oracleAuthority
#address = "3rGrMUKPVp8NzxC7pwxcj4hR3aHmCyKuFFVngH23UYTJ"
#
#[[test.validator.clone]] # oracleEscrow
#address = "Hy8KS7hSgHmBv7rxr2tkcgq8SrMar6NUvvhjRbZvwENt"
#
#[[test.validator.clone]] # oraclePermissions
#address = "Gs9ZxMG1sLM6JtoUpdPApErP6A4B4gLKPSn3XopMTswa"
#
