[provider]
cluster = "localnet"
wallet = "/Users/mac/.config/solana/id.json"

[test]
startup_wait = 10000

[test.validator]
url = "https://devnet.genesysgo.net/"

[[test.validator.clone]] # programID
address = "2TfB33aLaneQb5TNVwyDz3jSZXS6jdW2ARw1Dgf84XCG"

[[test.validator.clone]] # idlAddress
address = "CKwZcshn4XDvhaWVH9EXnk3iu19t6t5xP2Sy2pD6TRDp"

[[test.validator.clone]] # programState
address = "BYM81n8HvTJuqZU1PmTVcwZ9G8uoji7FKM6EaPkwphPt"

[[test.validator.clone]] # switchboardVault
address = "FVLfR6C2ckZhbSwBzZY4CX7YBcddUSge5BNeGQv5eKhy"

[[test.validator.clone]] # tokenWallet
address = "9mHKsQgdQGUYtZEcve2H5RMyvymyEeAcJJiHzvx6JSeA"

[[test.validator.clone]] # queue
address = "91vSGQhSRS9tFXZajXnj14qCVkqXecnnfpZQpSU7kJYc"

[[test.validator.clone]] # queueAuthority
address = "3rGrMUKPVp8NzxC7pwxcj4hR3aHmCyKuFFVngH23UYTJ"

[[test.validator.clone]] # queueBuffer
address = "7jYV1p5X4ZUaq8KaQUP2NiNqDdJVR4Watpn6treCaSC8"

[[test.validator.clone]] # crank
address = "6BXk2CyJ1gVkJr4TUNxKvpi4qHxn4gtuGDzhBz4KqYk7"

[[test.validator.clone]] # crankBuffer
address = "5zgm6MiuPhqQSM7C5ZemkMtHEzkbxNRhJ4zt5XXJEYwy"

[[test.validator.clone]] # oracle
address = "43vYNKe8sX9odEjpFo75s9Czqu1Yo4q7FVgz9aPFRqVy"

[[test.validator.clone]] # oracleAuthority
address = "3rGrMUKPVp8NzxC7pwxcj4hR3aHmCyKuFFVngH23UYTJ"

[[test.validator.clone]] # oracleEscrow
address = "2pdrSNuzPz1DBk1RXXJiPwHdH5HCeemfkxBryA8ovGf6"

[[test.validator.clone]] # oraclePermissions
address = "6EjsLQssxSWSnGJzQNHQkNCs5Z9QDAKji29gg2srGRRZ"
